export { MCP_ICON_PATHS, MCP_ICON_VIEWBOX } from './mcp-svg'
export {
  SEALGATE_E_PATH,
  SEALGATE_FRAME_PATH,
  SEALGATE_LOGO_VIEWBOX,
  SEALGATE_FILL_PATH,
  SEALGATE_STROKE_PATH
} from './sealgate-logo-svg'
export {
  OUTLOOK_SVG,
  OUTLOOK_SVG_VIEWBOX,
  SLACK_SVG,
  SLACK_SVG_VIEWBOX,
  GCAL_SVG,
  GCAL_SVG_VIEWBOX
} from './app-icons-svg'
export { ATTACKER_BODY_PATHS, ATTACKER_HIGHLIGHT_PATHS, ATTACKER_SVG_VIEWBOX } from './attacker-svg'
